MY-quicq/.devcontainer/quiz_app/config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'
  root "games#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  get    "/choices", to: "choices#index"
  resources :games, only: [:new, :index, :create, :edit, :update, :show]
  resources :questions, only: [:new, :create, :destroy, :index]
  resources :choices, only:[:index, :create, :destroy]
  resources :matches, only: [:create]
  get 'play/:match_id/:game_id', to: 'matches#play', as: :match_play
  patch 'play/:match_id/:game_id', to: 'matches#update', as: :match_update

  post 'questions/predict', :controller => 'questions', :action => 'predict'
end

MY-quicq/.devcontainer/quiz_app/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :match, optional: true
  validates :name, presence: true, length: { maximum: 12 }
 after_update_commit { GameBroadcastJob.perform_later self }

  scope :rank_sorted, -> {
    select("*,
            correct_quantities * 100 / question_quantities AS correct_rate,
            trunc(extract(
                second
                FROM
                  end_at - created_at
              )) AS answer_time,
            RANK() OVER(ORDER BY correct_quantities * 100 / question_quantities DESC, trunc(extract(
                    second
                    FROM
                      end_at - created_at
                  )) ASC) AS rank")
          .where.not(end_at: nil)
          .limit(20)
  }

  def correct_answers
    "#{correct_quantities}/#{question_quantities}"
  end

  def percentage_correct_answers
    calc_result = correct_quantities.to_f / question_quantities.to_f * 100
    calc_result.to_i
  end
end

MY-quicq/.devcontainer/quiz_app/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :is_session_game_id, only: :edit
  before_action :is_correct_game_id, only: :edit

  def show
    if @game = Game.find_by( id: params[:id] )
      reset_session
    else
      redirect_to root_path
    end
  end

  def new
    @game = Game.new
    @game.name = cookies[:game_name] if cookies[:game_name]
    @games = Game.rank_sorted
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      reset_session
      cookies.permanent[:game_name] = @game.name
      session[:game_id] = @game.id
      redirect_to edit_game_path(@game.id)
    else
      @games = Game.rank_sorted
      flash.now[:danger] = '名前が保存できませんでした（12文字以内）'
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @game = Game.find(params[:id])
    @question = Question.order("RANDOM()").limit(1)[0]
    correct_choice = Choice.find(@question.choice_id)
    wrong_choices = Choice.where.not(id: correct_choice.id).order("RANDOM()").limit(3)
    @choices = wrong_choices.map { |choice| {text: choice.text, is_correct: false} }
    @choices << { text: correct_choice.text, is_correct: true}
    @choices.shuffle!
  end

  def update
    game = Game.find(params[:id])
    game.correct_quantities += 1 if params[:question][:choice] == "true"
    if game.current_question_num == game.question_quantities
      game.end_at = Time.now
      game.save
      redirect_to game_path(game)
    else
      game.current_question_num += 1
      game.save
      redirect_to edit_game_path
    end
  end

  private
    def game_params
      params.require(:game).permit(:name)
    end

    def is_session_game_id
      redirect_to root_path if session[:game_id].nil?
    end

    def is_correct_game_id
      redirect_to root_path if session[:game_id] != params[:id].to_i
    end
end

MY-quicq/.devcontainer/quiz_app/app/helpers/games_helper.rb
module GamesHelper
  
  def display_end_at(time)
    format_at = I18n.l time
    format_at.gsub(/ /, '<br>').html_safe
  end
  
  def calc_question_progress(current_num, question_quantities)
    current_num * 100 / question_quantities
  end
  
  # modelで書くともっとシンプルになる
  # def correct_answers
  #   "#{@game.correct_quantities}/#{@game.question_quantities}"
  # end
    
  # def percentage_correct_answers
  #   calc_result = @game.correct_quantities.to_f / @game.question_quantities.to_f * 100
  #   calc_result.to_i
  # end
end

MY-quicq/.devcontainer/quiz_app/app/views/games/edit.html.erb
<div class="row">
  <div class="col s12 m8 l6 offset-m2 offset-l3 question-container">
    <div id="js-judgment-correct" class="question-judgment correct"></div>
    <div id="js-judgment-wrong" class="question-judgment wrong"></div>
    <div class="z-depth-1 question-image-frame mb-0">
      <%= image_tag @question.image.variant(:display).processed, class: "question-image",
                                                                 id: "js-question-image" %>
    </div>
    <div class="question-card z-depth-1 mb-0">
      <div class="question-name"><%= @game.name %></div>
      <div class="question-progress">
        <p class="number">
          <span class="current"><%= @game.current_question_num %></span>問目
        </p>
        <div class="progress">
          <div class="determinate" style="width: <%= calc_question_progress(@game.current_question_num, @game.question_quantities) %>%"></div>
        </div>
        <div class="correct">(正解: <%= @game.correct_quantities %>)</div>
      </div>
    </div>
    <%= form_with scope: :question,
                  url: game_path(params[:id]),
                  method: :patch,
                  html: {name: "answer_form"} do |f| %>
      <% @choices.each do |choice| %>
        <div>
          <label>
            <%= f.radio_button :choice, choice[:is_correct], class: "with-gap" %>
            <div class="waves-effect waves-light btn full mb-0">
              <%= choice[:text] %>
            </div>
          </label>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

MY-quicq/.devcontainer/quiz_app/app/views/games/new.html.erb
<%= render 'layouts/flash_messages' %>

<% if logged_in? %>
  <div class="row z-depth-1 start-card">
    <p class="bold admin-title">管理者メニュー</p>
    <div class="col s12 m8 l6 offset-m2 offset-l3">
      <%= link_to "問題の編集", questions_path, class: "waves-effect waves-light btn-large full mb-1"%>
      <%= link_to "選択肢の編集", choices_path,  class: "waves-effect waves-light btn-large full mb-1" %>
      <%= link_to "ログアウト", logout_path,
                             data: { "turbo-method": :delete },
                             class: "waves-effect waves-light btn-large full mb-1" %>
    </div>
  </div>
<% end %>
<div class="row z-depth-1 start-card">
  <p class="bold start-title">ゲームを始める</p>
  <%= form_with(model: @game, class: "col s12 m6 l4 offset-m3 offset-l4") do |f| %>
    <div class="mb-0">
      <%= f.label 'ニックネーム' %>
      <% if @game.name %>
        <%= f.text_field :name, placeholder: @game.name %>
      <% else %>
        <%= f.text_field :name %>
      <% end %>
    </div>
    <div class="center-align mb-1">
      <button type='submit' class="waves-effect waves-light btn-large full">1人用モード</button>
    </div>
  <% end %>
  <div class="col s12 m6 l4 offset-m3 offset-l4">
    <%= form_with(url: matches_path, method: :post, scope: :match, html: {name: "match_form"}) do |f| %>
      <%= f.hidden_field :name, value: @game.name %>
    <% end %>
    <div class="center-align">
      <button id='js-match-btn' class="waves-effect waves-light btn-large full">対戦モード</button>
    </div>
  </div>
</div>
<div class="z-depth-1 rank-card">
  <p class="bold rank-title">ランキング</p>
  <table class="striped">
    <thead>
      <tr>
        <th>順位</th>
        <th>ニックネーム</th>
        <th>正答率</th>
        <th>タイム</th>
        <th>日時</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
      <tr>
        <td><%= game.rank %></td>
        <td><%= game.name %></td>
        <td><%= game.correct_rate %>%</td>
        <td><%= game.answer_time.floor() %>秒</td>
        <td class="end-at"><%= display_end_at(game.end_at) %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

MY-quicq/.devcontainer/quiz_app/app/views/games/show.html.erb
<div class="row">
  <div class="result-card col s12 m8 l6 offset-m2 offset-l3 z-depth-1 center-align">
    <p><span class="bold"><%= @game.name %></span>さんの結果は...</p>
    <p class="result-text">正解率: <%= @game.correct_answers %> (<%= @game.percentage_correct_answers %>%)</p>
    <%= link_to "Top画面へ戻る", root_path, class: "waves-effect waves-light btn-large" %>
  </div>
</div>